steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/beauty-intelligence-platform-backend'
      - '-f'
      - 'Dockerfile.backend'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/beauty-intelligence-platform-backend'

images:
  - 'gcr.io/$PROJECT_ID/beauty-intelligence-platform-backend'